### ISSUE TITLE
release 1.0.6 is not reproducible

### ISSUE THREAD

**Issue by hboutemy** [codehaus-plexus/plexus-languages#59] opened 2021-01-12 07:17 UTC
timestamp of `META-INF/versions/9/module-info.class` is not reproducible

https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/codehaus/plexus/plexus-languages/plexus-languages-1.0.6.diffoscope

**Comment by rfscholte** [comment] 2021-01-12 08:05
I guess a bug in plexus archiver, right?

**Comment by hboutemy** [comment] 2021-01-12 09:18
I guess Maven JAR Plugin, on its calls to archive version-specific classes
but I need to investigate to be sure

**Comment by rfscholte** [comment] 2021-01-12 11:08
Now I remember, it is caused by https://github.com/codehaus-plexus/plexus-archiver/blob/master/src/main/java/org/codehaus/plexus/archiver/jar/JarToolModularJarArchiver.java

**Comment by hboutemy** [comment] 2021-01-13 08:20
oh nice: yes, this looks like the right location. Thank you for pointing out before I loose time looking at wrong location :)

is there a chance that we inject a timestamp to this process?
IIUC https://github.com/codehaus-plexus/plexus-archiver/blob/master/src/main/java/org/codehaus/plexus/archiver/jar/JarToolModularJarArchiver.java#L162 , it uses `jar` in-process CLI tool, and I don't see any parameter to define timestamp: would that mean that the only option is to modify timestamp on disk? (I don't like that idea...)

**Comment by hboutemy** [comment] 2021-01-13 08:21
notice: this discussion would probably be better done in plexus-archiver...
need to create an issue: I'll do it tonight if you don't beat me at it

**Comment by olamy** [comment] 2021-07-11 23:27
@hboutemy I guess we can close this one?

**Comment by hboutemy** [comment] 2021-07-12 05:27
@olamy sadly I'm not sure at all: this one is tricky given how it is done

**Comment by rfscholte** [comment] 2021-07-12 06:37
This one needs to be crosslinked with the ticket of plexus-archiver

**Comment by slachiewicz** [comment] 2021-08-22 13:14
https://github.com/codehaus-plexus/plexus-archiver/issues/164

**Comment by rfscholte** [comment] 2021-08-22 13:30
Let's keep it open until it is reproducible, otherwise it looks it is fixed (even though the fix is somewhere else)

**Comment by andpab** [comment] 2022-12-31 11:44
The crosslinked issue https://github.com/codehaus-plexus/plexus-archiver/issues/164 was apparently fixed by #205 and closed a few months ago. I think that means this one can be closed as well.

On a side note: How about spinning a new release of plexus-languages? The asm version updates would bring Java 19 and Java 20 bytecode support.

**Comment by hboutemy** [comment] 2023-01-01 16:04
requires maven-jar-plugin 3.3.0 https://issues.apache.org/jira/browse/MJAR-275

**Comment by slachiewicz** [comment] 2023-01-11 14:10
Thx for check ✅

**Closed** 2023-01-11 14:10 UTC
Labels: bug, dependencies
