### ISSUE TITLE
Dependency on original jar after repackaging is not picked up.

### ISSUE THREAD

**Issue by nickstolwijk** [codehaus-plexus/plexus-languages#48] opened 2020-10-27 12:46 UTC
We have a Integration Test module which has a dependency on the product module. However, the jar of the product module is repackaged into a Spring Boot layered jar and the original attached jar is renamed.

When I use this as a dependency, the LocationManager complains that it is not a jar file, which it certainly is.
`
[INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (integration-test) @ product.integratietests ---
[WARNING] Exception for 'C:\work\product\product\target\product.product-1.159.0-SNAPSHOT.jar.original'.
java.lang.IllegalArgumentException: 'C:\work\product\product\target\product.product-1.159.0-SNAPSHOT.jar.original' not allowed on the path, only outputDirectories and jars are accepted
    at org.codehaus.plexus.languages.java.jpms.LocationManager.resolvePath (LocationManager.java:335)
    at org.codehaus.plexus.languages.java.jpms.LocationManager.resolvePaths (LocationManager.java:201)
`
I have taken a look at the LocationManager and it checks only the extension. I have checked the JLS on Jar files and no where it declares that a jar file should have the .jar extension. [1] I think thus that this is not the correct way to identify a jar file.

[1] https://docs.oracle.com/javase/7/docs/technotes/guides/jar/jar.html

**Comment by rfscholte** [comment] 2020-10-27 16:28
The issue is not the Jar specification, but the JPMS specification, it only talks about jars: https://cr.openjdk.java.net/~mr/jigsaw/spec/jar.html
The implementation that verifies the File is at https://github.com/AdoptOpenJDK/openjdk-jdk/blob/7d41a54188f8d7c86c655c274bdeed602309a7f0/src/java.base/share/classes/jdk/internal/module/ModulePath.java#L306-L352

You can easy check it in JShell:
> java.lang.module.ModuleFinder.of(java.nio.file.Paths.get("product.product-1.159.0-SNAPSHOT.jar.original")).findAll()

Using a springboot application as a dependency can't be right, right?

**Comment by nickstolwijk** [comment] 2020-10-27 16:39
> Using a springboot application as a dependency can't be right, right?
That's right, the integration tests tests the application by starting the application in the test instead of starting the container or jar-file that comes out of the product module. I guess it is time to move them back into the product module instead of seperating them.

I just hadn't expected the LocationManager or even the JPMS specification treated a JAR file, as a file with a .jar extension. The JPMS spec even says: `There is no restriction on the name of a JAR file, it can be any legal file name on a particular platform.`.

For now I have told the failsafe plugin to not use the modular path and the classpath loader happily loads my .original jar file.

**Comment by rfscholte** [comment] 2020-10-27 17:18
closing as `not an issue/works as expected`

**Closed by rfscholte** 2020-10-27 17:18 UTC
